name: ML Workflow

on:
  workflow_dispatch:
    inputs:
      epochs:
        description: 'Number of epochs'
        required: true
        default: 20
      learning_rate:
        description: 'Learning rate'
        required: true
        default: 0.001
      batch_size:
        description: 'Batch size'
        required: true
        default: 32

jobs:
  train_and_evaluate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn tensorflow matplotlib mlflow

    - name: Train Model
      run: python create_model.py ${{ github.event.inputs.epochs }} ${{ github.event.inputs.learning_rate }} ${{ github.event.inputs.batch_size }}

    - name: Evaluate Model
      run: python evaluate.py ${{ github.run_number }}